uploads = []
outputs = []

[[generated]]
id = "IempbwdpHUvRUpz-wuF4D"
uri = "file://artifacts/school-website/public/emblem.png"
type = "image"
title = "School Emblem Logo"

[[generated]]
id = "9hHfBLHsQAuTX6gD9qQOV"
uri = "file://artifacts/school-website/public/hero.png"
type = "image"
title = "Hero school building"

[[generated]]
id = "Y2FnhmbDOaZtk_yLG-OcE"
uri = "file://artifacts/school-website/public/staff1.png"
type = "image"
title = "Principal Portrait"

[[generated]]
id = "mWm7ep1LRmF76OB_-678j"
uri = "file://artifacts/school-website/public/activity1.png"
type = "image"
title = "Students playing soccer"

[[generated]]
id = "fV5yMOLFYZuZVUlx-Sk3T"
uri = "file://artifacts/school-website/public/science-lab.png"
type = "image"
title = "Science lab experiment"
