import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import statsRouter from "./stats";
import newsRouter from "./news";
import activitiesRouter from "./activities";
import teachersRouter from "./teachers";
import studentsRouter from "./students";
import contactsRouter from "./contacts";
import settingsRouter from "./settings";
import uploadRouter from "./upload";
import classroomsRouter from "./classrooms";
import gradesRouter from "./grades";
import reportsRouter from "./reports";
import documentsRouter from "./documents";
import documentCategoriesRouter from "./document-categories";
import subjectConfigsRouter from "./subject-configs";
import subjectsRouter from "./subjects";
import geoRouter from "./geo";
import leaveRequestsRouter from "./leave-requests";
import attendanceRouter from "./attendance";
import idCardTemplatesRouter from "./id_card_templates";
import libraryRouter from "./library";
import schedulesRouter from "./schedules";
import scheduleRouter from "./schedule";
import telegramRouter from "./telegram";
import telegramInboxRouter from "./telegram-inbox";
import parentsRouter from "./parents";
import { backupsRouter } from "./backups";
import qrLoginRouter from "./qr-login";

const router: IRouter = Router();

router.get("/ping", (req, res) => res.json({ message: "API is reachable" }));
router.use(healthRouter);
router.use(authRouter);
router.use(statsRouter);
router.use(newsRouter);
router.use(activitiesRouter);
router.use(teachersRouter);
router.use(classroomsRouter);
router.use(documentsRouter);
router.use(documentCategoriesRouter);
router.use(studentsRouter);
router.use(contactsRouter);
router.use(settingsRouter);
router.use(uploadRouter);
router.use("/grades", gradesRouter);
router.use("/reports", reportsRouter);
router.use(subjectConfigsRouter);
router.use("/subjects", subjectsRouter);
router.use(geoRouter);
router.use(leaveRequestsRouter);
router.use(attendanceRouter);
router.use(idCardTemplatesRouter);
router.use(libraryRouter);
router.use("/schedules", schedulesRouter);
router.use("/schedule", scheduleRouter);
router.use(telegramRouter);
router.use("/telegram", telegramInboxRouter);
router.use(parentsRouter);
router.use("/backups", backupsRouter);
router.use(qrLoginRouter);

export default router;

