#!/bin/bash
# ---------------------------------------------------------
# Phlov Meas Secondary School - WAL Archive Management
# ---------------------------------------------------------
# This script manages the Write-Ahead Log (WAL) archives 
# generated by PostgreSQL. It cleans up old WAL files and 
# syncs the latest archives to the cloud.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ -f "$DIR/.env" ]; then
    source "$DIR/.env"
fi

chmod +x "$DIR/cloud-sync.sh"

BACKUP_ROOT_DIR=${BACKUP_ROOT_DIR:-"/var/backups/phlov_meas"}
WAL_ARCHIVE_DIR="$BACKUP_ROOT_DIR/db/wal_archive"
RETENTION_DAYS=7

mkdir -p "$WAL_ARCHIVE_DIR"

echo "================================================="
echo "Starting WAL Archive Management at $(date)"
echo "================================================="

# 1. Clean up WAL files older than RETENTION_DAYS
echo "Applying WAL retention policy ($RETENTION_DAYS days)..."
find "$WAL_ARCHIVE_DIR" -type f -mtime +$RETENTION_DAYS -delete

# Note: In a production PostgreSQL environment, pg_archivecleanup is preferred
# if you know the oldest WAL file required by the oldest base backup. 
# Using `find -mtime` is a simpler alternative for bounded retention.

# 2. Sync to cloud
echo "Syncing new WAL files to cloud..."
"$DIR/cloud-sync.sh"

echo "WAL Archive Management completed."
exit 0
